### ISSUE TITLE
如何让pen浏览器 preview的时候不把标签的属性去掉？

### ISSUE THREAD

**Issue by Pillar-Zhang** [sofish/pen#183]
需求是 我在这个编辑器上进行了扩展 增加了自定义的标签 发现一旦进行 ctrl + v 操作 标签上的类名 就消失了 发现在这个面板也是 比如下面的这个标签：

<div class="section scrollspy"><i class="color-orange">[</i><h6> 0 </h6><i class="color-orange">]</i></div>

然后点 preview 的时候 类名也会去掉 怎么可以规避这个 过滤呢？

**Comment by Pillar-Zhang** [comment]
“<div class="section scrollspy"><i class="color-orange">[</i><h6> 0 </h6><i class="color-orange">]</i></div>”

**Comment by Pillar-Zhang** [comment]
`<div class="section scrollspy"><i class="color-orange">[</i><h6> 0 </h6><i class="color-orange">]</i></div>`

**Comment by sofish** [comment]
在文档里没有写清楚，你可以看一下这个 https://github.com/sofish/pen/blob/master/src/pen.js#L92 , 在 config 里去定义什么 attr 和 tag 是需要 clean 的。

**Comment by Pillar-Zhang** [comment]
好的  完美解决问题了 谢谢 果然问原作者是解决问题的最快途径
