### ISSUE TITLE
How to tag selected code?

### ISSUE THREAD

**Issue by vstath** [sofish/pen#189]
I am trying to have a button that tags the selected text with markdown of my choice. 

Is there some option to add the markdown tag of my choice via code (for the selected text). So, for example, I select "ABC" from the content and I fire an event that will make it into "_ * * ABC * * _" (Bold/Italics at once) 

I love this editor as it's small, versatile and outputs MD (which I am using).

Thanks!

**Comment by sofish** [comment]
will not support in near future
